test_that("test for changing number to name of the month", {
  expect_equal(num_to_month(1), "janvier")
  expect_equal(num_to_month(2), "février")
  expect_equal(num_to_month(3), "mars")
  expect_equal(num_to_month(4), "avril")
  expect_equal(num_to_month(5), "mai")
  expect_equal(num_to_month(6), "juin")
  expect_equal(num_to_month(7), "juillet")
  expect_equal(num_to_month(8), "août")
  expect_equal(num_to_month(9), "septembre")
  expect_equal(num_to_month(10), "octobre")
  expect_equal(num_to_month(11), "novembre")
  expect_equal(num_to_month(12), "décembre")
})
